// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbyADbRAoNGlpQNVI3tkP1vGyzWW6Hlgc',
    appId: '1:946133701885:web:2761c60632372465421a94',
    messagingSenderId: '946133701885',
    projectId: 'selfrival-59aff',
    authDomain: 'selfrival-59aff.firebaseapp.com',
    databaseURL: 'https://selfrival-59aff-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'selfrival-59aff.firebasestorage.app',
    measurementId: 'G-ZK6J1C5Y26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrz3zkZFiwVBU2BmOXRki1IMIJ8peRuUU',
    appId: '1:946133701885:android:b4293e2f07f79158421a94',
    messagingSenderId: '946133701885',
    projectId: 'selfrival-59aff',
    databaseURL: 'https://selfrival-59aff-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'selfrival-59aff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMXGbYCfT7t-acfDOcWkn2h2DlZ7_IUQY',
    appId: '1:946133701885:ios:849a470bd72368bd421a94',
    messagingSenderId: '946133701885',
    projectId: 'selfrival-59aff',
    databaseURL: 'https://selfrival-59aff-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'selfrival-59aff.firebasestorage.app',
    iosBundleId: 'com.selfrival.selfrival',
  );
}
